[package]
name = "ArborSealPolicy"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.71.0" }

[addresses]
Arbor_seal_policy = "0x0"
